# Generated by Django 3.2.13 on 2022-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20221222_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='age',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grandparent',
            name='age',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='age',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
