# Generated by Django 3.2.13 on 2022-12-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_auto_20221222_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
