# Generated by Django 3.2.13 on 2022-12-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='sibling',
            field=models.ManyToManyField(to='parents.Siblings'),
        ),
        migrations.AddField(
            model_name='parents',
            name='parent',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='parents.grandparent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siblings',
            name='age',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
